apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: current-time-api
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:Cyb8r/kubernetes-ci-cd-demo.git
    targetRevision: main
    path: manifests
  destination:
    server: https://192.168.49.2:8443
    namespace: default
  project: default
